# ruff: noqa: N999
# Generated by Django 5.1.8 on 2025-07-25 00:32
import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0238_risk_acceptance_permanent_and_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="risk_acceptance_request",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("webhooks", "webhooks"),
                    ("alert", "alert"),
                ],
                default=("alert", "alert"),
                help_text="Get notified when a Risk Acceptance requires approval",
                max_length=33,
                verbose_name="Risk Acceptance Requests",
            ),
        ),
    ]
